import type { ComposeSettings } from "@/lib/api";

export const DEFAULT_COMPOSE: ComposeSettings = {
  headline_style: "bold_red",
  headline_bg: "#E31B23",
  headline_color: "#FFFFFF",
  headline_font_size: 42,
  headline_align: "center",
  headline_max_width_pct: 0.85,
  headline_x: 0.5,
  headline_y: 0.15,
  logo_x: 0.85,
  logo_y: 0.78,
  logo_scale: 0.18,
  progress_enabled: false,
  progress_color: "#E31B23",
  progress_height_pct: 0.04,
  overlay_pos_x: 0.5,
  overlay_pos_y: 0.5,
  ig_bg_color: "#FFFFFF",
  ig_text_color: "#141414",
  ig_avatar_size: 72,
  ig_username_size: 34,
  ig_caption_size: 28,
};
