
import { copy } from "@/lib/i18n/copy";
import type { TemplateInfo } from "@/lib/api";

/** Mirrors backend/templates.py — instant preview without waiting on /api/templates. */
export const STATIC_TEMPLATES: TemplateInfo[] = [
  {
    id: "reels_split",
    name: "Reels 9:16 (split topo/baixo)",
    get description() { return copy("Vídeo original embaixo, espaço em cima pra imagem ou vídeo."); },
    aspect: "9:16",
    width: 1080,
    height: 1920,
    overlay_region: { x: 0, y: 0, w: 1080, h: 960 },
    video_region: { x: 0, y: 960, w: 1080, h: 960 },
    subtitle_safe_y: 1820,
    needs_overlay: true,
    overlay_accepts: ["image", "video"],
    layout: "vstack",
    header_region: null,
    left_panel_region: null,
    right_panel_region: null,
    subtitle_safe_x: null,
  },
  {
    id: "ig_square",
    get name() { return copy("Instagram 1:1 (quadrado)"); },
    get description() { return copy("Vídeo original embaixo, imagem em cima. Perfeito pro feed."); },
    aspect: "1:1",
    width: 1080,
    height: 1080,
    overlay_region: { x: 0, y: 0, w: 1080, h: 540 },
    video_region: { x: 0, y: 540, w: 1080, h: 540 },
    subtitle_safe_y: 1020,
    needs_overlay: true,
    overlay_accepts: ["image", "video"],
    layout: "vstack",
    header_region: null,
    left_panel_region: null,
    right_panel_region: null,
    subtitle_safe_x: null,
  },
  {
    id: "reels_full",
    get name() { return copy("Reels 9:16 (tela cheia)"); },
    get description() { return copy("Vídeo vertical 9:16 com crop central — sem overlay."); },
    aspect: "9:16",
    width: 1080,
    height: 1920,
    overlay_region: { x: 0, y: 0, w: 0, h: 0 },
    video_region: { x: 0, y: 0, w: 1080, h: 1920 },
    subtitle_safe_y: 1820,
    needs_overlay: false,
    overlay_accepts: [],
    layout: "vstack",
    header_region: null,
    left_panel_region: null,
    right_panel_region: null,
    subtitle_safe_x: null,
  },
  {
    id: "choquei_image",
    get name() { return copy("Choquei (imagem em cima)"); },
    get description() { return copy("70% vídeo embaixo, imagem estática em cima — estilo viral."); },
    aspect: "9:16",
    width: 1080,
    height: 1920,
    overlay_region: { x: 0, y: 0, w: 1080, h: 576 },
    video_region: { x: 0, y: 576, w: 1080, h: 1344 },
    subtitle_safe_y: 1580,
    needs_overlay: true,
    overlay_accepts: ["image"],
    layout: "vstack",
    header_region: null,
    left_panel_region: null,
    right_panel_region: null,
    subtitle_safe_x: null,
  },
  {
    id: "choquei_video",
    get name() { return copy("Choquei (vídeo em cima)"); },
    get description() { return copy("70% vídeo embaixo, vídeo loop em cima — estilo viral."); },
    aspect: "9:16",
    width: 1080,
    height: 1920,
    overlay_region: { x: 0, y: 0, w: 1080, h: 576 },
    video_region: { x: 0, y: 576, w: 1080, h: 1344 },
    subtitle_safe_y: 1580,
    needs_overlay: true,
    overlay_accepts: ["video"],
    layout: "vstack",
    header_region: null,
    left_panel_region: null,
    right_panel_region: null,
    subtitle_safe_x: null,
  },
];
